const fs = require('fs').promises;
const path = require('path');
const { randomUUID } = require('crypto');
const { exec } = require('child_process');

// MetadataStore - JSON file I/O, in-memory caching, CRUD operations
class MetadataStore {
  constructor() {
    this.cache = new Map();
    this.database = null;
  }

  /**
   * Initialize with a database service instance for CRUD operations
   * @param {DatabaseService} databaseService
   */
  initializeWithDatabase(databaseService) {
    this.database = databaseService;
  }

  /**
   * Upsert a media entry into the database
   * @param {object} entry - Media entry data
   */
  async upsertMediaEntry(entry) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.upsertMediaEntry(entry);
  }

  /**
   * Safely upsert a media entry, preserving all existing fields
   * @param {object} entry - Media entry data (can be partial)
   */


  async safeUpsertMediaEntry(entry) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    
    // Get existing entry to preserve all fields
    const existingEntry = await this.getMediaEntry(entry.id);
    
    if (existingEntry) {
      // Merge new data with existing data, preserving all fields
      const mergedEntry = {
        ID: existingEntry.ID,
        PATH: existingEntry.PATH,
        NAME: existingEntry.NAME,
        TYPE: existingEntry.TYPE,
        RATING: existingEntry.RATING,
        DATE_ADDED: existingEntry.DATE_ADDED,
        PROGRESS: existingEntry.PROGRESS,
        PAGE_COUNT: existingEntry.PAGE_COUNT,
        THUMBNAIL_PROCESSED: existingEntry.THUMBNAIL_PROCESSED,
        IN_COLLECTION: existingEntry.IN_COLLECTION,
        // Override with new values if provided
        ...entry,
        // Ensure critical fields are preserved
        id: entry.id || existingEntry.ID,
        path: entry.path || existingEntry.PATH,
        name: entry.name || existingEntry.NAME,
        type: entry.type || existingEntry.TYPE,
        rating: entry.rating !== undefined ? entry.rating : existingEntry.RATING,
        dateAdded: entry.dateAdded || existingEntry.DATE_ADDED,
        progress: entry.progress !== undefined ? entry.progress : existingEntry.PROGRESS,
        pageCount: entry.pageCount !== undefined ? entry.pageCount : existingEntry.PAGE_COUNT,
        thumbnailProcessed: entry.thumbnailProcessed !== undefined ? entry.thumbnailProcessed : existingEntry.THUMBNAIL_PROCESSED,
        inCollection: entry.inCollection !== undefined ? entry.inCollection : existingEntry.IN_COLLECTION
      };
      
      return await this.database.upsertMediaEntry(mergedEntry);
    } else {
      // New entry, use provided data
      return await this.database.upsertMediaEntry({
        ...entry,
        inCollection: entry.inCollection || 0
      });
    }
  }

  /**
   * Upsert a collection into the database
   * @param {object} collection - Collection data
   */
  async upsertCollection(collection) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.upsertCollection(collection);
  }

  /**
   * Safely upsert a collection, preserving all existing fields
   * @param {object} collection - Collection data (can be partial)
   */
  async safeUpsertCollection(collection) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    
    // Get existing collection to preserve all fields
    const existingCollection = await this.getCollection(collection.id);
    
    if (existingCollection) {
      // Merge new data with existing data, preserving all fields
      const mergedCollection = {
        ID: existingCollection.ID,
        PATH: existingCollection.PATH,
        NAME: existingCollection.NAME,
        AUTO_GENERATED: existingCollection.AUTO_GENERATED,
        RATING: existingCollection.RATING,
        LAST_OPENED_ID: existingCollection.LAST_OPENED_ID,
        THUMBNAIL_ID: existingCollection.THUMBNAIL_ID,
        // Override with new values if provided
        ...collection,
        // Ensure critical fields are preserved
        id: collection.id || existingCollection.ID,
        path: collection.path || existingCollection.PATH,
        name: collection.name || existingCollection.NAME,
        autoGenerated: collection.autoGenerated !== undefined ? collection.autoGenerated : existingCollection.AUTO_GENERATED,
        rating: collection.rating !== undefined ? collection.rating : existingCollection.RATING,
        lastOpenedId: collection.lastOpenedId !== undefined ? collection.lastOpenedId : existingCollection.LAST_OPENED_ID,
        thumbnailId: collection.thumbnailId !== undefined ? collection.thumbnailId : existingCollection.THUMBNAIL_ID
      };
      
      return await this.database.upsertCollection(mergedCollection);
    } else {
      // New collection, use provided data
      return await this.database.upsertCollection({
        ...collection,
        rating: collection.rating || 0,
        lastOpenedId: collection.lastOpenedId || null,
        thumbnailId: collection.thumbnailId || null
      });
    }
  }

  /**
   * Add a media entry to a collection
   * @param {string} collectionId
   * @param {string} mediaEntryId
   * @param {number} sortOrder
   */
  async addCollectionMember(collectionId, mediaEntryId, sortOrder) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.addCollectionMember(collectionId, mediaEntryId, sortOrder);
  }

  /**
   * Get a media entry by ID
   * @param {string} id
   */
  async getMediaEntry(id) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.getMediaEntry(id);
  }

  /**
   * Get all media entries
   */
  async getAllMediaEntries() {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.getAllMediaEntries();
  }

  /**
   * Get all collections
   */
  async getAllCollections() {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.getAllCollections();
  }

  /**
   * Get all collections with their members
   */
  async getCollectionsWithMembers() {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.getCollectionsWithMembers();
  }
  /**
   * Gets a single collection's metadata
   * @param {string} collectionId 
   */
  async getCollection(collectionId) {
    // This passes the request down to the DatabaseService
    return await this.database.getCollection(collectionId);
  }
  

  /**
   * Get all members of a collection
   * @param {string} collectionId
   */
  async getCollectionMembers(collectionId) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.getCollectionMembers(collectionId);
  }

  /**
   * Get all collections that contain a specific entry
   * @param {string} entryId - Entry ID to look up
   * @returns {Promise<Array>} - Array of collection memberships
   */
  async getCollectionMembersForEntry(entryId) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.getCollectionMembersForEntry(entryId);
  }

  /**
   * Remove a media entry from a collection
   * @param {string} collectionId - Collection ID
   * @param {string} mediaEntryId - Media entry ID
   */
  async removeCollectionMember(collectionId, mediaEntryId) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.removeCollectionMember(collectionId, mediaEntryId);
  }

  /**
   * Update IN_COLLECTION status for a media entry
   * @param {string} entryId - Media entry ID
   * @param {number} inCollection - 1 if in collection, 0 otherwise
   */
  async updateMediaEntryCollectionStatus(entryId, inCollection) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.updateMediaEntryCollectionStatus(entryId, inCollection);
  }

  /**
   * Get all user-created collections (AUTO_GENERATED = FALSE)
   * @returns {Promise<Array>} - Array of user collections
   */
  async getUserCollections() {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.getUserCollections();
  }

  /**
   * Delete a collection by ID
   * @param {string} collectionId - Collection ID to delete
   */
  async deleteCollection(collectionId) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.deleteCollection(collectionId);
  }

  /**
   * Set rating for a media entry
   * @param {string} entryId - Media entry ID
   * @param {number} rating - Rating value (0-100)
   */
  async setEntryRating(entryId, rating) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.setEntryRating(entryId, rating);
  }

  /**
   * Set rating for a collection
   * @param {string} collectionId - Collection ID
   * @param {number} rating - Rating value (0-100)
   */
  async setCollectionRating(collectionId, rating) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.setCollectionRating(collectionId, rating);
  }

  /**
   * Update collection's last opened entry
   * @param {string} collectionId - Collection ID
   * @param {string} lastOpenedId - Last opened entry ID
   */
  async updateCollectionLastOpened(collectionId, lastOpenedId) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.updateCollectionLastOpened(collectionId, lastOpenedId);
  }

  /**
   * Update collection thumbnail
   * @param {string} collectionId - Collection ID
   * @param {string} thumbnailId - Media entry ID to use as thumbnail
   */
  async setCollectionThumbnail(collectionId, thumbnailId) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.setCollectionThumbnail(collectionId, thumbnailId);
  }

  /**
   * Update collection member sort order
   * @param {string} collectionId - Collection ID
   * @param {string} mediaEntryId - Media entry ID
   * @param {number} sortOrder - New sort order
   */
  async updateCollectionMemberSortOrder(collectionId, mediaEntryId, sortOrder) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.updateCollectionMemberSortOrder(collectionId, mediaEntryId, sortOrder);
  }

  /**
   * Add a tag to a media entry
   * @param {string} entryId - Media entry ID
   * @param {string} tagName - Tag name
   */
  async addTagToEntry(entryId, tagName) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.addTagToEntry(entryId, tagName);
  }

  /**
   * Remove a tag from a media entry
   * @param {string} entryId - Media entry ID
   * @param {string} tagName - Tag name
   */
  async removeTagFromEntry(entryId, tagName) {
    if (!this.database) throw new Error('MetadataStore not initialized with database');
    return await this.database.removeTagFromEntry(entryId, tagName);
  }

  /**
   * Performs a breadth-first traversal of the directory tree up to depth 2
   * and ensures each folder has a .per_id file with a UUID v4
   * @param {string} rootPath - The root directory to scan
   * @returns {Promise<{success: boolean, created: number, error?: string}>}
   */
  async ensureFolderIDs(rootPath) {
    try {
      const stats = await fs.stat(rootPath);
      if (!stats.isDirectory()) {
        return { success: false, error: 'Root path is not a directory' };
      }

      let createdCount = 0;
      const queue = [{ path: rootPath, depth: 0 }];

      while (queue.length > 0) {
        const { path: currentPath, depth } = queue.shift();

        // Stop at depth 2
        if (depth > 2) continue;

        // Skip the root folder (depth 0) - only create .per_id in subfolders
        if (depth > 0) {
          // Check for .per_id file
          const perIdPath = path.join(currentPath, '.per_id');
          try {
            await fs.access(perIdPath);
            // .per_id exists, skip
          } catch (accessError) {
            // .per_id doesn't exist, create it
            try {
              const uuid = randomUUID();
              await fs.writeFile(perIdPath, uuid, 'utf8');
              // Set hidden attribute on Windows
              if (process.platform === 'win32') {
                exec(`attrib +h "${perIdPath}"`, (err) => {
                  if (err) console.warn(`Failed to set hidden attribute for ${perIdPath}: ${err.message}`);
                });
              }
              createdCount++;
            } catch (writeError) {
              if (writeError.code === 'EACCES' || writeError.code === 'EPERM') {
                // Permission denied, skip this folder
                console.warn(`Permission denied for folder: ${currentPath}`);
                continue;
              }
              throw writeError;
            }
          }
        }

        // If we're at depth < 2, add subdirectories to queue
        if (depth < 2) {
          try {
            const entries = await fs.readdir(currentPath, { withFileTypes: true });
            for (const entry of entries) {
              if (entry.isDirectory() && !entry.name.startsWith('.')) {
                queue.push({
                  path: path.join(currentPath, entry.name),
                  depth: depth + 1
                });
              }
            }
          } catch (readdirError) {
            if (readdirError.code === 'EACCES' || readdirError.code === 'EPERM') {
              // Permission denied, skip this folder
              console.warn(`Permission denied to read folder: ${currentPath}`);
              continue;
            }
            throw readdirError;
          }
        }
      }

      return { success: true, created: createdCount };
    } catch (error) {
      return { success: false, error: error.message };
    }
  }
}

module.exports = MetadataStore;
